#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Representation of a VLAN which does not exist in the database.

.PARAMETER Vid
No description available.
.PARAMETER Group
No description available.
.OUTPUTS

AvailableVLAN<PSCustomObject>
#>

function Initialize-AvailableVLAN {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${Vid},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Group}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AvailableVLAN' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Vid) {
            throw "invalid value for 'Vid', 'Vid' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "vid" = ${Vid}
            "group" = ${Group}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AvailableVLAN<PSCustomObject>

.DESCRIPTION

Convert from JSON to AvailableVLAN<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AvailableVLAN<PSCustomObject>
#>
function ConvertFrom-JsonToAvailableVLAN {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AvailableVLAN' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AvailableVLAN
        $AllProperties = ("vid", "group")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'vid' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "vid"))) {
            throw "Error! JSON cannot be serialized due to the required property 'vid' missing."
        } else {
            $Vid = $JsonParameters.PSobject.Properties["vid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "group"))) {
            throw "Error! JSON cannot be serialized due to the required property 'group' missing."
        } else {
            $Group = $JsonParameters.PSobject.Properties["group"].value
        }

        $PSO = [PSCustomObject]@{
            "vid" = ${Vid}
            "group" = ${Group}
        }

        return $PSO
    }

}

