#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Represents an object related through a ForeignKey field. On write, it accepts a primary key (PK) value or a dictionary of attributes which can be used to uniquely identify the related object. This class should be subclassed to return a full representation of the related object on read.

.PARAMETER Username
Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
.OUTPUTS

NestedUserRequest<PSCustomObject>
#>

function Initialize-NestedUserRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^[\w.@+-]+$")]
        [String]
        ${Username}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => NestedUserRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Username) {
            throw "invalid value for 'Username', 'Username' cannot be null."
        }

        if ($Username.length -gt 150) {
            throw "invalid value for 'Username', the character length must be smaller than or equal to 150."
        }

        if ($Username.length -lt 1) {
            throw "invalid value for 'Username', the character length must be great than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "username" = ${Username}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NestedUserRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to NestedUserRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NestedUserRequest<PSCustomObject>
#>
function ConvertFrom-JsonToNestedUserRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => NestedUserRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in NestedUserRequest
        $AllProperties = ("username")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'username' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "username"))) {
            throw "Error! JSON cannot be serialized due to the required property 'username' missing."
        } else {
            $Username = $JsonParameters.PSobject.Properties["username"].value
        }

        $PSO = [PSCustomObject]@{
            "username" = ${Username}
        }

        return $PSO
    }

}

