#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Adds support for custom fields and tags.

.PARAMETER Group
No description available.
.PARAMETER InterfaceType
No description available.
.PARAMETER InterfaceId
No description available.
.PARAMETER Priority
No description available.
.OUTPUTS

PatchedWritableFHRPGroupAssignmentRequest<PSCustomObject>
#>

function Initialize-PatchedWritableFHRPGroupAssignmentRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Group},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${InterfaceType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${InterfaceId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Priority}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PatchedWritableFHRPGroupAssignmentRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($InterfaceId -and $InterfaceId -gt 9223372036854775807) {
          throw "invalid value for 'InterfaceId', must be smaller than or equal to 9223372036854775807."
        }

        if ($InterfaceId -and $InterfaceId -lt 0) {
          throw "invalid value for 'InterfaceId', must be greater than or equal to 0."
        }

        if ($Priority -and $Priority -gt 255) {
          throw "invalid value for 'Priority', must be smaller than or equal to 255."
        }

        if ($Priority -and $Priority -lt 0) {
          throw "invalid value for 'Priority', must be greater than or equal to 0."
        }


        $PSO = [PSCustomObject]@{
            "group" = ${Group}
            "interface_type" = ${InterfaceType}
            "interface_id" = ${InterfaceId}
            "priority" = ${Priority}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PatchedWritableFHRPGroupAssignmentRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to PatchedWritableFHRPGroupAssignmentRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PatchedWritableFHRPGroupAssignmentRequest<PSCustomObject>
#>
function ConvertFrom-JsonToPatchedWritableFHRPGroupAssignmentRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PatchedWritableFHRPGroupAssignmentRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PatchedWritableFHRPGroupAssignmentRequest
        $AllProperties = ("group", "interface_type", "interface_id", "priority")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "group"))) { #optional property not found
            $Group = $null
        } else {
            $Group = $JsonParameters.PSobject.Properties["group"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "interface_type"))) { #optional property not found
            $InterfaceType = $null
        } else {
            $InterfaceType = $JsonParameters.PSobject.Properties["interface_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "interface_id"))) { #optional property not found
            $InterfaceId = $null
        } else {
            $InterfaceId = $JsonParameters.PSobject.Properties["interface_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "priority"))) { #optional property not found
            $Priority = $null
        } else {
            $Priority = $JsonParameters.PSobject.Properties["priority"].value
        }

        $PSO = [PSCustomObject]@{
            "group" = ${Group}
            "interface_type" = ${InterfaceType}
            "interface_id" = ${InterfaceId}
            "priority" = ${Priority}
        }

        return $PSO
    }

}

