#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ClusterType' {
    Context 'ClusterType' {
        It 'Initialize-ClusterType' {
            # a simple test to create an object
            #$NewObject = Initialize-ClusterType -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -Name "TEST_VALUE" -Slug "TEST_VALUE" -Description "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE" -Created "TEST_VALUE" -LastUpdated "TEST_VALUE" -ClusterCount "TEST_VALUE"
            #$NewObject | Should -BeOfType ClusterType
            #$NewObject.property | Should -Be 0
        }
    }
}
