#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ConfigTemplateRequest' {
    Context 'ConfigTemplateRequest' {
        It 'Initialize-ConfigTemplateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-ConfigTemplateRequest -Name "TEST_VALUE" -Description "TEST_VALUE" -EnvironmentParams "TEST_VALUE" -TemplateCode "TEST_VALUE" -DataSource "TEST_VALUE" -Tags "TEST_VALUE"
            #$NewObject | Should -BeOfType ConfigTemplateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
