#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ConsoleServerPortTemplate' {
    Context 'ConsoleServerPortTemplate' {
        It 'Initialize-ConsoleServerPortTemplate' {
            # a simple test to create an object
            #$NewObject = Initialize-ConsoleServerPortTemplate -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -DeviceType "TEST_VALUE" -ModuleType "TEST_VALUE" -Name "TEST_VALUE" -Label "TEST_VALUE" -Type "TEST_VALUE" -Description "TEST_VALUE" -Created "TEST_VALUE" -LastUpdated "TEST_VALUE"
            #$NewObject | Should -BeOfType ConsoleServerPortTemplate
            #$NewObject.property | Should -Be 0
        }
    }
}
