#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ContactAssignmentRequest' {
    Context 'ContactAssignmentRequest' {
        It 'Initialize-ContactAssignmentRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-ContactAssignmentRequest -ContentType "TEST_VALUE" -ObjectId "TEST_VALUE" -Contact "TEST_VALUE" -Role "TEST_VALUE" -Priority "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType ContactAssignmentRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
