#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'Contact' {
    Context 'Contact' {
        It 'Initialize-Contact' {
            # a simple test to create an object
            #$NewObject = Initialize-Contact -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -Group "TEST_VALUE" -Name "TEST_VALUE" -Title "TEST_VALUE" -Phone "TEST_VALUE" -Email "TEST_VALUE" -Address "TEST_VALUE" -Link "TEST_VALUE" -Description "TEST_VALUE" -Comments "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE" -Created "TEST_VALUE" -LastUpdated "TEST_VALUE"
            #$NewObject | Should -BeOfType Contact
            #$NewObject.property | Should -Be 0
        }
    }
}
