#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ContactAssignment' {
    Context 'ContactAssignment' {
        It 'Initialize-ContactAssignment' {
            # a simple test to create an object
            #$NewObject = Initialize-ContactAssignment -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -ContentType "TEST_VALUE" -ObjectId "TEST_VALUE" -Object "TEST_VALUE" -Contact "TEST_VALUE" -Role "TEST_VALUE" -Priority "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE" -Created "TEST_VALUE" -LastUpdated "TEST_VALUE"
            #$NewObject | Should -BeOfType ContactAssignment
            #$NewObject.property | Should -Be 0
        }
    }
}
