#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'GenericObjectRequest' {
    Context 'GenericObjectRequest' {
        It 'Initialize-GenericObjectRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-GenericObjectRequest -ObjectType "TEST_VALUE" -ObjectId "TEST_VALUE"
            #$NewObject | Should -BeOfType GenericObjectRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
