#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'ImageAttachment' {
    Context 'ImageAttachment' {
        It 'Initialize-ImageAttachment' {
            # a simple test to create an object
            #$NewObject = Initialize-ImageAttachment -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -ContentType "TEST_VALUE" -ObjectId "TEST_VALUE" -Parent "TEST_VALUE" -Name "TEST_VALUE" -Image "TEST_VALUE" -ImageHeight "TEST_VALUE" -ImageWidth "TEST_VALUE" -Created "TEST_VALUE" -LastUpdated "TEST_VALUE"
            #$NewObject | Should -BeOfType ImageAttachment
            #$NewObject.property | Should -Be 0
        }
    }
}
