#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'JobStatus' {
    Context 'JobStatus' {
        It 'Initialize-JobStatus' {
            # a simple test to create an object
            #$NewObject = Initialize-JobStatus -Value "TEST_VALUE" -Label "TEST_VALUE"
            #$NewObject | Should -BeOfType JobStatus
            #$NewObject.property | Should -Be 0
        }
    }
}
