#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedVRFRequest' {
    Context 'NestedVRFRequest' {
        It 'Initialize-NestedVRFRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedVRFRequest -Name "TEST_VALUE" -Rd "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedVRFRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
