#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedManufacturerRequest' {
    Context 'NestedManufacturerRequest' {
        It 'Initialize-NestedManufacturerRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedManufacturerRequest -Name "TEST_VALUE" -Slug "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedManufacturerRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
