#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedIPSecProfile' {
    Context 'NestedIPSecProfile' {
        It 'Initialize-NestedIPSecProfile' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedIPSecProfile -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedIPSecProfile
            #$NewObject.property | Should -Be 0
        }
    }
}
