#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedIPSecPolicyRequest' {
    Context 'NestedIPSecPolicyRequest' {
        It 'Initialize-NestedIPSecPolicyRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedIPSecPolicyRequest -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedIPSecPolicyRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
