#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedFHRPGroupRequest' {
    Context 'NestedFHRPGroupRequest' {
        It 'Initialize-NestedFHRPGroupRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedFHRPGroupRequest -Protocol "TEST_VALUE" -GroupId "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedFHRPGroupRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
