#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedL2VPNTermination' {
    Context 'NestedL2VPNTermination' {
        It 'Initialize-NestedL2VPNTermination' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedL2VPNTermination -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -L2vpn "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedL2VPNTermination
            #$NewObject.property | Should -Be 0
        }
    }
}
