#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'NestedIKEPolicyRequest' {
    Context 'NestedIKEPolicyRequest' {
        It 'Initialize-NestedIKEPolicyRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-NestedIKEPolicyRequest -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType NestedIKEPolicyRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
