#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PaginatedContactList' {
    Context 'PaginatedContactList' {
        It 'Initialize-PaginatedContactList' {
            # a simple test to create an object
            #$NewObject = Initialize-PaginatedContactList -Count "TEST_VALUE" -Next "TEST_VALUE" -Previous "TEST_VALUE" -Results "TEST_VALUE"
            #$NewObject | Should -BeOfType PaginatedContactList
            #$NewObject.property | Should -Be 0
        }
    }
}
