#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedWritableCustomFieldChoiceSetRequest' {
    Context 'PatchedWritableCustomFieldChoiceSetRequest' {
        It 'Initialize-PatchedWritableCustomFieldChoiceSetRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedWritableCustomFieldChoiceSetRequest -Name "TEST_VALUE" -Description "TEST_VALUE" -BaseChoices "TEST_VALUE" -ExtraChoices "TEST_VALUE" -OrderAlphabetically "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedWritableCustomFieldChoiceSetRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
