#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedWritableServiceRequest' {
    Context 'PatchedWritableServiceRequest' {
        It 'Initialize-PatchedWritableServiceRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedWritableServiceRequest -Device "TEST_VALUE" -VirtualMachine "TEST_VALUE" -Name "TEST_VALUE" -Ports "TEST_VALUE" -Protocol "TEST_VALUE" -Ipaddresses "TEST_VALUE" -Description "TEST_VALUE" -Comments "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedWritableServiceRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
