#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedWritableWirelessLinkRequest' {
    Context 'PatchedWritableWirelessLinkRequest' {
        It 'Initialize-PatchedWritableWirelessLinkRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedWritableWirelessLinkRequest -InterfaceA "TEST_VALUE" -InterfaceB "TEST_VALUE" -Ssid "TEST_VALUE" -Status "TEST_VALUE" -Tenant "TEST_VALUE" -AuthType "TEST_VALUE" -AuthCipher "TEST_VALUE" -AuthPsk "TEST_VALUE" -Description "TEST_VALUE" -Comments "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedWritableWirelessLinkRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
