#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedWritableTokenRequest' {
    Context 'PatchedWritableTokenRequest' {
        It 'Initialize-PatchedWritableTokenRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedWritableTokenRequest -User "TEST_VALUE" -Expires "TEST_VALUE" -LastUsed "TEST_VALUE" -Key "TEST_VALUE" -WriteEnabled "TEST_VALUE" -Description "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedWritableTokenRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
