#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedContactRoleRequest' {
    Context 'PatchedContactRoleRequest' {
        It 'Initialize-PatchedContactRoleRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedContactRoleRequest -Name "TEST_VALUE" -Slug "TEST_VALUE" -Description "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedContactRoleRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
