#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedTagRequest' {
    Context 'PatchedTagRequest' {
        It 'Initialize-PatchedTagRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedTagRequest -Name "TEST_VALUE" -Slug "TEST_VALUE" -Color "TEST_VALUE" -Description "TEST_VALUE" -ObjectTypes "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedTagRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
