#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PatchedWritableDeviceBayRequest' {
    Context 'PatchedWritableDeviceBayRequest' {
        It 'Initialize-PatchedWritableDeviceBayRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-PatchedWritableDeviceBayRequest -Device "TEST_VALUE" -Name "TEST_VALUE" -Label "TEST_VALUE" -Description "TEST_VALUE" -InstalledDevice "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType PatchedWritableDeviceBayRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
