#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TagRequest' {
    Context 'TagRequest' {
        It 'Initialize-TagRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-TagRequest -Name "TEST_VALUE" -Slug "TEST_VALUE" -Color "TEST_VALUE" -Description "TEST_VALUE" -ObjectTypes "TEST_VALUE"
            #$NewObject | Should -BeOfType TagRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
