#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'TokenProvision' {
    Context 'TokenProvision' {
        It 'Initialize-TokenProvision' {
            # a simple test to create an object
            #$NewObject = Initialize-TokenProvision -Id "TEST_VALUE" -Url "TEST_VALUE" -Display "TEST_VALUE" -User "TEST_VALUE" -Created "TEST_VALUE" -Expires "TEST_VALUE" -LastUsed "TEST_VALUE" -Key "TEST_VALUE" -WriteEnabled "TEST_VALUE" -Description "TEST_VALUE"
            #$NewObject | Should -BeOfType TokenProvision
            #$NewObject.property | Should -Be 0
        }
    }
}
