#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WebhookRequest' {
    Context 'WebhookRequest' {
        It 'Initialize-WebhookRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-WebhookRequest -Name "TEST_VALUE" -Description "TEST_VALUE" -PayloadUrl "TEST_VALUE" -HttpMethod "TEST_VALUE" -HttpContentType "TEST_VALUE" -AdditionalHeaders "TEST_VALUE" -BodyTemplate "TEST_VALUE" -Secret "TEST_VALUE" -SslVerification "TEST_VALUE" -CaFilePath "TEST_VALUE" -CustomFields "TEST_VALUE" -Tags "TEST_VALUE"
            #$NewObject | Should -BeOfType WebhookRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
