#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WirelessLANAuthType' {
    Context 'WirelessLANAuthType' {
        It 'Initialize-WirelessLANAuthType' {
            # a simple test to create an object
            #$NewObject = Initialize-WirelessLANAuthType -Value "TEST_VALUE" -Label "TEST_VALUE"
            #$NewObject | Should -BeOfType WirelessLANAuthType
            #$NewObject.property | Should -Be 0
        }
    }
}
