#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WritableConsoleServerPortTemplateRequest' {
    Context 'WritableConsoleServerPortTemplateRequest' {
        It 'Initialize-WritableConsoleServerPortTemplateRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-WritableConsoleServerPortTemplateRequest -DeviceType "TEST_VALUE" -ModuleType "TEST_VALUE" -Name "TEST_VALUE" -Label "TEST_VALUE" -Type "TEST_VALUE" -Description "TEST_VALUE"
            #$NewObject | Should -BeOfType WritableConsoleServerPortTemplateRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
