#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WritableModuleTypeRequest' {
    Context 'WritableModuleTypeRequest' {
        It 'Initialize-WritableModuleTypeRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-WritableModuleTypeRequest -Manufacturer "TEST_VALUE" -Model "TEST_VALUE" -PartNumber "TEST_VALUE" -Weight "TEST_VALUE" -WeightUnit "TEST_VALUE" -Description "TEST_VALUE" -Comments "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType WritableModuleTypeRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
