#
# NetBox REST API
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
# Version: 3.7.8 (3.7)
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'WritableConsolePortRequest' {
    Context 'WritableConsolePortRequest' {
        It 'Initialize-WritableConsolePortRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-WritableConsolePortRequest -Device "TEST_VALUE" -Module "TEST_VALUE" -Name "TEST_VALUE" -Label "TEST_VALUE" -Type "TEST_VALUE" -Speed "TEST_VALUE" -Description "TEST_VALUE" -MarkConnected "TEST_VALUE" -Tags "TEST_VALUE" -CustomFields "TEST_VALUE"
            #$NewObject | Should -BeOfType WritableConsolePortRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
